/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Khuyenmai;

import java.awt.Graphics;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class KhuyenMai1 extends javax.swing.JFrame {

    private Repositories rp = new Repositories();
    private DefaultTableModel mol = new DefaultTableModel();
    private DefaultTableModel model = new DefaultTableModel();
    private int i = -1;

    /**
     * Creates new form KhuyenMai
     */
    public KhuyenMai1() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.fillTable(rp.getAll());
    }

    void fillTable(ArrayList<Model_Khuyenmai> list) {
        int i = 1;
        mol = (DefaultTableModel) tbl_Khuyenmai.getModel();
        mol.setRowCount(0);
        for (Model_Khuyenmai x : list) {
            mol.addRow(new Object[]{i++, x.getMaKhuyenMai(), x.getTenKhuyenMai(), x.getNgayBatDau(), x.getNgayKetThuc(), x.getHinhThuc(), x.getGiatiSP()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_MaKM = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_TenKM = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_Ngaytao = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btn_Them = new javax.swing.JButton();
        btn_Sua = new javax.swing.JButton();
        btn_Xoa = new javax.swing.JButton();
        txt_Ngayketthuc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_Hinhthuc = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_Giatrisanpham = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btn_Tim = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_Khuyenmai = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Mã KM:");

        jLabel5.setText("Tên KM:");

        jLabel3.setText("Ngày Tạo:");

        jLabel4.setText("Ngày Kết Thúc:");

        btn_Them.setBackground(new java.awt.Color(255, 204, 51));
        btn_Them.setForeground(new java.awt.Color(0, 0, 0));
        btn_Them.setText("Mới");
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });

        btn_Sua.setBackground(new java.awt.Color(255, 204, 51));
        btn_Sua.setForeground(new java.awt.Color(0, 0, 0));
        btn_Sua.setText("Update");
        btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaActionPerformed(evt);
            }
        });

        btn_Xoa.setBackground(new java.awt.Color(255, 204, 51));
        btn_Xoa.setForeground(new java.awt.Color(0, 0, 0));
        btn_Xoa.setText("Delete");
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });

        jLabel6.setText("Hình thức :");

        jLabel7.setText("Giá trị sản phẩm :");

        btn_Tim.setBackground(new java.awt.Color(255, 204, 0));
        btn_Tim.setForeground(new java.awt.Color(0, 0, 0));
        btn_Tim.setText("Tìm Kiếm ");
        btn_Tim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_Giatrisanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Hinhthuc, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txt_Ngaytao, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_MaKM, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_TenKM, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                            .addComponent(txt_Ngayketthuc, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(94, 94, 94)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Them)
                            .addComponent(btn_Sua)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btn_Tim)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_Xoa))))
                .addContainerGap(312, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_MaKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(btn_Tim)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(txt_TenKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(btn_Them))
                .addGap(10, 10, 10)
                .addComponent(txt_Ngaytao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Sua)
                .addGap(3, 3, 3)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Ngayketthuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Xoa)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_Hinhthuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(txt_Giatrisanpham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 47, Short.MAX_VALUE))
        );

        tbl_Khuyenmai.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tbl_Khuyenmai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Mã KM", "Tên KM", "Ngày tạo ", "Ngày Kết Thúc", "Hinh thuc", "Giá trị sản phẩm"
            }
        ));
        tbl_Khuyenmai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_KhuyenmaiMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_Khuyenmai);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(346, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_KhuyenmaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_KhuyenmaiMouseClicked
        // TODO add your handling code here:
        i = tbl_Khuyenmai.getSelectedRow();
        txt_MaKM.setText(tbl_Khuyenmai.getValueAt(i, 1).toString());
        txt_TenKM.setText(tbl_Khuyenmai.getValueAt(i, 2).toString());
        txt_Ngaytao.setText(tbl_Khuyenmai.getValueAt(i, 3).toString());
        txt_Ngayketthuc.setText(tbl_Khuyenmai.getValueAt(i, 4).toString());
        txt_Hinhthuc.setText(tbl_Khuyenmai.getValueAt(i, 5).toString());
        txt_Giatrisanpham.setText(tbl_Khuyenmai.getValueAt(i, 6).toString());
    }//GEN-LAST:event_tbl_KhuyenmaiMouseClicked

    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
        // TODO add your handling code here:
        i = tbl_Khuyenmai.getSelectedRow();
        if(i==-1){
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn dòng");
        }else{
            String maSua = txt_MaKM.getText().toString();
            if(this.readFrom() != null){
                if(rp.Sua(this.readFrom(), maSua)>0){
                    JOptionPane.showMessageDialog(this,"Bạn đã sửa thành công");
                    this.fillTable(rp.getAll());
                }else{
                    JOptionPane.showConfirmDialog(this,"Bạn chưa sửa được");
                }
            }
        }
    }//GEN-LAST:event_btn_SuaActionPerformed

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
        // TODO add your handling code here:
        if(this.readFrom()!=null){
            String maXoa = txt_MaKM.getText().toString();
            if(rp.Xoa(maXoa)>0){
                JOptionPane.showConfirmDialog(this,"Bạn xóa thông tin thành công");
                this.fillTable(rp.getAll());
            }else{
                JOptionPane.showConfirmDialog(this,"Xóa thông tin thất bại");
            }
        }
    }//GEN-LAST:event_btn_XoaActionPerformed

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        // TODO add your handling code here:
        if (this.readFrom() != null) {
            if (rp.Them(this.readFrom()) > 0) {
                JOptionPane.showMessageDialog(this, "Bạn đã thêm thành công");
                this.fillTable(rp.getAll());
            } else {
                JOptionPane.showMessageDialog(this, "Thêm thất bại");
            }
        }
        txt_MaKM.setText("");
        txt_TenKM.setText("");
        txt_Ngaytao.setText("");
        txt_Ngayketthuc.setText("");
        txt_Hinhthuc.setText("");
        txt_Giatrisanpham.setText("");
        
    }//GEN-LAST:event_btn_ThemActionPerformed

    private void btn_TimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimActionPerformed
        // TODO add your handling code here:
        String MaKM = txt_MaKM.getText().trim();
        if(rp.timkiem(MaKM).isEmpty()){
            JOptionPane.showMessageDialog(this,"Thông tin bạn tìm kiếm không có trong bảng");
        }else{
            this.fillTable(rp.timkiem(MaKM));
            JOptionPane.showMessageDialog(this, "Thông tin bạn tìm kiếm có trong bảng");
        }
    }//GEN-LAST:event_btn_TimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KhuyenMai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KhuyenMai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KhuyenMai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KhuyenMai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KhuyenMai1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Sua;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_Tim;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tbl_Khuyenmai;
    private javax.swing.JTextField txt_Giatrisanpham;
    private javax.swing.JTextField txt_Hinhthuc;
    private javax.swing.JTextField txt_MaKM;
    private javax.swing.JTextField txt_Ngayketthuc;
    private javax.swing.JTextField txt_Ngaytao;
    private javax.swing.JTextField txt_TenKM;
    // End of variables declaration//GEN-END:variables
Model_Khuyenmai readFrom() {
        String MaKhuyenMai;
        String TenKhuyenMai;
        String NgayBatDau;
        String NgayKetThuc;
        String hinhThuc;
        float giatiSP;
        MaKhuyenMai = txt_TenKM.getText();
        TenKhuyenMai = txt_TenKM.getText();
        NgayBatDau = txt_Ngaytao.getText();
        NgayKetThuc = txt_Ngayketthuc.getText();
        hinhThuc = txt_Hinhthuc.getText();
        giatiSP = Float.parseFloat(txt_Giatrisanpham.getText().toString());
        return new Model_Khuyenmai(MaKhuyenMai, TenKhuyenMai, NgayBatDau, NgayKetThuc, hinhThuc, giatiSP);

    }
}
